"""
Agent module.

This module contains the core Agent implementation and configuration.
"""

from .agent import Agent
from .config import AgentConfig
from .governance import (
    SchemaGovernanceManager,
    SchemaGovernancePolicy,
    SchemaGovernanceStack,
    build_schema_governance_stack,
)
from .sql_governance import (
    SqlGovernanceManager,
    SqlGovernancePolicy,
    SqlGovernanceProfile,
    SqlGovernanceStack,
    analyze_sql_text,
    analyze_sql_shape,
    build_sql_governance_profile,
    build_sql_governance_prompt_block,
    build_sql_governance_recap_block,
    build_sql_governance_stack,
    infer_profile_from_message,
    parse_sql_governance_profile,
    sql_governance_rejection_reason,
    sql_semantics_rejection_reason,
)
from .query_plan import (
    QueryPlan,
    QueryPlanCheck,
    QueryPlanFilter,
    QueryPlanMode,
    QueryPlanRiskAssessment,
    assess_query_plan_risk,
    build_schema_evidence,
    parse_query_plan_mode,
    validate_query_plan_evidence,
    validate_query_plan_intent,
    validate_sql_against_query_plan,
)
from .failure_recovery import (
    FailureCategory,
    FailureDecision,
    FailureRecoveryState,
    RecoveryAction,
    build_failure_recovery_prompt,
    classify_tool_failure,
)
from .sql_review import (
    SqlIntentReview,
    SqlReviewMode,
    parse_sql_intent_review,
    parse_sql_review_mode,
    requires_sql_review,
    sql_fingerprint,
)
from .semantic_contract import (
    SemanticContractCatalog,
    SemanticContractCheck,
    SemanticContractMode,
    SemanticMetricContract,
    format_semantic_contracts_for_llm,
    load_semantic_contract_catalog,
    parse_semantic_contract_mode,
    validate_query_plan_semantic_contracts,
    validate_sql_against_semantic_contracts,
)

__all__ = [
    "Agent",
    "AgentConfig",
    "SchemaGovernanceManager",
    "SchemaGovernancePolicy",
    "SchemaGovernanceStack",
    "build_schema_governance_stack",
    "SqlGovernanceManager",
    "SqlGovernancePolicy",
    "SqlGovernanceProfile",
    "SqlGovernanceStack",
    "analyze_sql_text",
    "analyze_sql_shape",
    "build_sql_governance_profile",
    "build_sql_governance_prompt_block",
    "build_sql_governance_recap_block",
    "build_sql_governance_stack",
    "infer_profile_from_message",
    "parse_sql_governance_profile",
    "sql_governance_rejection_reason",
    "sql_semantics_rejection_reason",
    "QueryPlan",
    "QueryPlanCheck",
    "QueryPlanFilter",
    "QueryPlanMode",
    "QueryPlanRiskAssessment",
    "assess_query_plan_risk",
    "build_schema_evidence",
    "parse_query_plan_mode",
    "validate_query_plan_evidence",
    "validate_query_plan_intent",
    "validate_sql_against_query_plan",
    "FailureCategory",
    "FailureDecision",
    "FailureRecoveryState",
    "RecoveryAction",
    "build_failure_recovery_prompt",
    "classify_tool_failure",
    "SqlIntentReview",
    "SqlReviewMode",
    "parse_sql_intent_review",
    "parse_sql_review_mode",
    "requires_sql_review",
    "sql_fingerprint",
    "SemanticContractCatalog",
    "SemanticContractCheck",
    "SemanticContractMode",
    "SemanticMetricContract",
    "format_semantic_contracts_for_llm",
    "load_semantic_contract_catalog",
    "parse_semantic_contract_mode",
    "validate_query_plan_semantic_contracts",
    "validate_sql_against_semantic_contracts",
]
